### ISSUE TITLE
Standard Bi-Touch Environment Not Released?

### ISSUE THREAD

**Issue by milesprieb** [dexterousrobot/tactile_sim#1]
I am testing out the Tactile Gym 2.0 with the Bi-Touch branch here: https://github.com/yijionglin/tactile_gym/tree/Bi-Touch, and I have noticed that the "load_standard_bitouch_environment()" function that is imported from tactile_sim has not been implemented in tactile_sim.utils.setup_pb_utils. Is there an unreleased branch that has the Bi-Touch simulation environment?

**Comment by yijionglin** [comment]
Hi,

Thanks for your interest in our work!

We have already released our Beta version of Tactile Sim [here](https://github.com/yijionglin/tactile_sim/tree/Bi-Touch) for the Bi-Touch.

All the best,
Yijiong
